---
- name: Install ELK Stack (Elasticsearch, Logstash, Kibana)
  hosts: my_servers
  become: yes
  vars:
    elasticsearch_version: "7.x"

  tasks:
    - name: Add Elasticsearch GPG key
      rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      yum_repository:
        name: elasticsearch
        description: "Elasticsearch repository for {{ elasticsearch_version }}"
        baseurl: "https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/yum"
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Elasticsearch
      yum:
        name: elasticsearch
        state: present

    - name: Enable and start Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes
        state: started

    - name: Install Logstash
      yum:
        name: logstash
        state: present

    - name: Enable and start Logstash service
      systemd:
        name: logstash
        enabled: yes
        state: started

    - name: Install Kibana
      yum:
        name: kibana
        state: present

    - name: Enable and start Kibana service
      systemd:
        name: kibana
        enabled: yes
        state: started

    - name: Ensure Elasticsearch is running
      systemd:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Ensure Logstash is running
      systemd:
        name: logstash
        state: started
        enabled: yes

    - name: Ensure Kibana is running
      systemd:
        name: kibana
        state: started
        enabled: yes
